package haven.automated;

import haven.Coord;
import haven.Equipory;
import haven.GItem;
import haven.GameUI;
import haven.Inventory;
import haven.WItem;
import haven.Widget;
import haven.automated.helpers.FishingAtlas;
import haven.res.ui.stackinv.ItemStack;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Owns cursor cleanup, deliberate hand-slot placement, and restoration of displaced items. */
final class FishingHandManager {
    private static final int LEFT_HAND_SLOT = 6;
    private static final int RIGHT_HAND_SLOT = 7;
    private static final long MOVE_TIMEOUT_MS = 4000;
    private final GameUI gui;
    private final FishingItemLocator items;
    private final List<SavedHandItem> displaced = new ArrayList<>();

    FishingHandManager(GameUI gui, FishingItemLocator items) {
        this.gui = gui;
        this.items = items;
    }

    boolean stowFishingCursor() throws InterruptedException {
        if(gui.vhand == null)
            return(true);
        FishingAtlas.Part held = FishingAtlas.classify(FishingItemMetadata.name(gui.vhand),
                FishingItemMetadata.resource(gui.vhand));
        if(held != FishingAtlas.Part.POLE && held != FishingAtlas.Part.LINE &&
                held != FishingAtlas.Part.HOOK && held != FishingAtlas.Part.BAIT &&
                held != FishingAtlas.Part.LURE)
            return(false);
        Coord room = roomFor(gui.maininv, gui.vhand);
        if(room == null)
            return(false);
        gui.maininv.wdgmsg("drop", room);
        return(await(() -> gui.vhand == null));
    }

    WItem movePoleToMainInventory(String poleName, WItem pole) throws InterruptedException {
        if(pole == null || pole.item == null)
            return(null);
        GItem identity = pole.item;
        if(items.findPoleInHands(poleName, identity) == null)
            return(pole);
        if(roomFor(gui.maininv, pole) == null)
            return(null);
        identity.wdgmsg("transfer", Coord.z);
        if(!await(() -> items.findPoleInHands(poleName, identity) == null))
            return(null);
        return(items.findPole(poleName, identity));
    }

    WItem equipPole(String poleName, WItem pole) throws InterruptedException {
        if(pole == null || pole.item == null)
            return(null);
        WItem equipped = items.findPoleInHands(poleName, pole.item);
        if(equipped != null)
            return(equipped);

        Equipory equipory = gui.getequipory();
        if(equipory == null)
            return(null);
        int slot = emptyHand(equipory);
        if(slot < 0) {
            slot = displaceableHand(equipory);
            if(slot < 0 || !displace(equipory.slots[slot], slot))
                return(null);
        }

        FishingEquipment.ItemData expected = FishingItemMetadata.describe(pole);
        GItem moving = pole.item;
        Inventory originalInventory = Inventory.fromWidget(pole.parent);

        // This is the exact message generated by Shift+left-click on the rod. The
        // server, rather than client-side slot guesses, chooses the valid hand.
        shiftTransfer(pole);
        WItem result = awaitEquipped(expected, moving);
        if(result != null)
            return(result);

        /*
         * Shift-transfer from an equipped belt can first route the rod into the main
         * inventory. If that distinct transition occurred, perform the same gesture
         * once from main inventory. Never repeat it against an unchanged source.
         */
        WItem current = items.findPole(poleName, moving);
        Inventory currentInventory = current == null ? null : Inventory.fromWidget(current.parent);
        if(current != null && originalInventory != gui.maininv && currentInventory == gui.maininv) {
            shiftTransfer(current);
            return(awaitEquipped(expected, moving));
        }
        return(null);
    }

    boolean restoreDisplacedHands() throws InterruptedException {
        if(displaced.isEmpty())
            return(true);
        Equipory equipory = gui.getequipory();
        if(equipory == null || gui.maininv == null)
            return(false);

        for(int slot : new int[]{LEFT_HAND_SLOT, RIGHT_HAND_SLOT}) {
            WItem item = equipory.slots[slot];
            if(item != null && FishingAtlas.classify(FishingItemMetadata.name(item),
                    FishingItemMetadata.resource(item)) == FishingAtlas.Part.POLE) {
                if(roomFor(gui.maininv, item) == null)
                    return(false);
                GItem moving = item.item;
                moving.wdgmsg("transfer", Coord.z);
                if(!await(() -> equipory.slots[slot] == null || equipory.slots[slot].item != moving))
                    return(false);
            }
        }

        boolean restored = true;
        for(SavedHandItem saved : new ArrayList<>(displaced)) {
            if(equipory.slots[saved.slot] != null) {
                restored = false;
                continue;
            }
            WItem candidate = findSavedItem(saved);
            if(candidate == null || equipInSlot(candidate, saved.slot) == null) {
                restored = false;
                continue;
            }
            displaced.remove(saved);
        }
        return(restored);
    }

    private boolean displace(WItem item, int slot) throws InterruptedException {
        if(item == null || isBucket(item) || roomFor(gui.maininv, item) == null)
            return(false);
        SavedHandItem saved = new SavedHandItem(slot, FishingItemMetadata.describe(item));
        GItem moving = item.item;
        moving.wdgmsg("transfer", Coord.z);
        if(!await(() -> {
            Equipory equipory = gui.getequipory();
            return(equipory == null || equipory.slots[slot] == null || equipory.slots[slot].item != moving);
        }))
            return(false);
        displaced.add(saved);
        return(true);
    }

    private WItem equipInSlot(WItem item, int slot) throws InterruptedException {
        Equipory equipory = gui.getequipory();
        if(equipory == null)
            return(null);
        CursorOrigin origin = new CursorOrigin(item);
        FishingEquipment.ItemData expected = FishingItemMetadata.describe(item);
        GItem moving = item.item;
        moving.wdgmsg("take", Coord.z);
        if(!await(() -> gui.vhand != null && gui.vhand.item == moving))
            return(null);
        equipory.wdgmsg("drop", slot);
        WItem result = awaitEquipped(expected, moving);
        if(result == null)
            origin.returnHeld(gui);
        return(result);
    }

    private WItem awaitEquipped(FishingEquipment.ItemData expected, GItem original)
            throws InterruptedException {
        long deadline = System.currentTimeMillis() + MOVE_TIMEOUT_MS;
        while(System.currentTimeMillis() < deadline) {
            WItem item = findEquipped(expected, original);
            if(item != null && (gui.vhand == null || gui.vhand.item != original))
                return(item);
            Thread.sleep(50);
        }
        return(null);
    }

    private WItem findEquipped(FishingEquipment.ItemData expected, GItem original) {
        Equipory equipory = gui.getequipory();
        if(equipory == null)
            return(null);
        for(int slot : new int[]{LEFT_HAND_SLOT, RIGHT_HAND_SLOT}) {
            WItem item = equipory.slots[slot];
            if(item == null || item.item == null)
                continue;
            if(item.item == original)
                return(item);
            FishingEquipment.ItemData actual = FishingItemMetadata.describe(item);
            if(!expected.resourceName.isEmpty() && expected.resourceName.equals(actual.resourceName) ||
                    expected.resourceName.isEmpty() && expected.displayName.equals(actual.displayName))
                return(item);
        }
        return(null);
    }

    private WItem findSavedItem(SavedHandItem saved) {
        WItem closest = null;
        double distance = Double.MAX_VALUE;
        for(WItem item : FishingInventory.equipmentItems(gui)) {
            FishingEquipment.ItemData data = FishingItemMetadata.describe(item);
            if(!saved.data.resourceName.equals(data.resourceName))
                continue;
            double next = qualityDistance(saved.data.quality, data.quality);
            if(next < distance) {
                closest = item;
                distance = next;
            }
        }
        return(closest);
    }

    private static void shiftTransfer(WItem item) {
        Coord center = new Coord(item.sz.x / 2, item.sz.y / 2);
        item.item.wdgmsg("transfer", center, 1);
    }

    private static int emptyHand(Equipory equipory) {
        for(int slot : new int[]{LEFT_HAND_SLOT, RIGHT_HAND_SLOT}) {
            if(equipory.slots[slot] == null)
                return(slot);
        }
        return(-1);
    }

    private static int displaceableHand(Equipory equipory) {
        for(int slot : new int[]{LEFT_HAND_SLOT, RIGHT_HAND_SLOT}) {
            if(equipory.slots[slot] != null && !isBucket(equipory.slots[slot]))
                return(slot);
        }
        return(-1);
    }

    private static boolean isBucket(WItem item) {
        String name = FishingItemMetadata.name(item).toLowerCase(Locale.ROOT);
        String resource = FishingItemMetadata.resource(item).toLowerCase(Locale.ROOT);
        return(name.contains("bucket") || resource.contains("bucket"));
    }

    static Coord roomFor(Inventory inventory, WItem item) {
        if(inventory == null || item == null)
            return(null);
        int width = Math.max(1, (item.sz.x + Inventory.sqsz.x - 1) / Inventory.sqsz.x);
        int height = Math.max(1, (item.sz.y + Inventory.sqsz.y - 1) / Inventory.sqsz.y);
        return(inventory.isRoom(width, height));
    }

    private static boolean await(Check check) throws InterruptedException {
        long deadline = System.currentTimeMillis() + MOVE_TIMEOUT_MS;
        while(System.currentTimeMillis() < deadline) {
            if(check.ready())
                return(true);
            Thread.sleep(50);
        }
        return(check.ready());
    }

    private static double qualityDistance(Double first, Double second) {
        if(first == null || second == null)
            return(first == second ? 0 : Double.MAX_VALUE / 2);
        return(Math.abs(first - second));
    }

    private interface Check { boolean ready(); }

    private static final class CursorOrigin {
        final Widget parent;
        final Coord coordinate;

        CursorOrigin(WItem item) {
            parent = item.parent;
            coordinate = Inventory.fromWidget(parent) == null ? null : item.c.div(Inventory.sqsz);
        }

        void returnHeld(GameUI gui) throws InterruptedException {
            if(gui.vhand == null)
                return;
            if(parent instanceof ItemStack) {
                parent.wdgmsg("drop");
                if(await(() -> gui.vhand == null))
                    return;
            }
            Inventory inventory = Inventory.fromWidget(parent);
            Inventory target = inventory == null ? gui.maininv : inventory;
            Coord destination = coordinate == null ? roomFor(target, gui.vhand) : coordinate;
            if(target != null && destination != null) {
                target.wdgmsg("drop", destination);
                await(() -> gui.vhand == null);
            }
        }
    }

    private static final class SavedHandItem {
        final int slot;
        final FishingEquipment.ItemData data;

        SavedHandItem(int slot, FishingEquipment.ItemData data) {
            this.slot = slot;
            this.data = data;
        }
    }
}
