package io.havenbot.protocol;

public enum BotEventType {
    BOT_REGISTERED,
    HEARTBEAT,
    SESSION_CHANGED,
    FAST_STATE_UPDATE,
    STATE_SNAPSHOT,
    TASK_STARTED,
    TASK_PROGRESS,
    TASK_COMPLETED,
    TASK_FAILED,
    ACTIVITY_EVENT,
    TAKEOVER_CHANGED,
    LIVE_FRAME_READY,
    SCREENSHOT_READY,
    CLIENT_ERROR
}
