// =============================================================================
// Tile Collector - File Watcher (chokidar)
// =============================================================================
// Watches a directory for new tile files generated by Haven & Hearth.
// Registers them in the database and broadcasts updates via WebSocket.
// =============================================================================

const chokidar = require('chokidar');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const { v4: uuidv4 } = require('uuid');
const { getDb, logActivity } = require('../database/db');
const { broadcastTileUpdate, broadcastTileActivity } = require('../server/websocket');
const config = require('../shared/config');

class TileCollector {
    constructor() {
        this.watcher = null;
        this.isRunning = false;
        this.isPaused = false;
        this.sessionId = uuidv4();
        this.tileCount = 0;
        this.pendingStitchCount = 0;
    }

    start() {
        const watchPath = path.resolve(config.haven.mapPath);

        if (!fs.existsSync(watchPath)) {
            console.warn(`[Collector] Watch path does not exist: ${watchPath}`);
            console.warn('[Collector] Creating directory and waiting for tiles...');
            fs.mkdirSync(watchPath, { recursive: true });
        }

        console.log(`[Collector] Watching: ${watchPath}`);
        console.log(`[Collector] Session: ${this.sessionId}`);

        // Register session in database
        try {
            const db = getDb();
            db.run(
                'INSERT INTO sessions (id, server, source) VALUES (?, ?, ?)',
                [this.sessionId, config.haven.defaultServer, 'collector']
            );
        } catch (err) {
            console.warn('[Collector] Could not register session:', err.message);
        }

        this.watcher = chokidar.watch(path.join(watchPath, 'tile_*.png'), {
            persistent: true,
            ignoreInitial: false,
            awaitWriteFinish: {
                stabilityThreshold: 1000,
                pollInterval: 200
            }
        });

        this.watcher.on('add', (filePath) => this.handleNewTile(filePath));
        this.watcher.on('change', (filePath) => this.handleNewTile(filePath));
        this.watcher.on('error', (err) => console.error('[Collector] Watcher error:', err));

        this.isRunning = true;
        console.log('[Collector] Started');
    }

    stop() {
        if (this.watcher) {
            this.watcher.close();
            this.watcher = null;
        }
        this.isRunning = false;
        console.log('[Collector] Stopped');
    }

    pause() {
        this.isPaused = true;
        console.log('[Collector] Paused');
    }

    resume() {
        this.isPaused = false;
        console.log('[Collector] Resumed');
    }

    handleNewTile(filePath) {
        if (this.isPaused) return;

        const filename = path.basename(filePath);
        const match = filename.match(/^tile_(-?\d+)_(-?\d+)\.png$/);

        if (!match) {
            console.warn(`[Collector] Skipping non-tile file: ${filename}`);
            return;
        }

        const x = parseInt(match[1]);
        const y = parseInt(match[2]);
        const server = config.haven.defaultServer;
        const mapId = 'default';

        try {
            // Copy tile to our storage
            const destDir = path.resolve(config.storage.tilesDir, server);
            if (!fs.existsSync(destDir)) {
                fs.mkdirSync(destDir, { recursive: true });
            }

            const destPath = path.join(destDir, filename);
            fs.copyFileSync(filePath, destPath);

            // Compute hash
            const buffer = fs.readFileSync(destPath);
            const hash = crypto.createHash('md5').update(buffer).digest('hex');

            // Register in database
            const db = getDb();
            db.run(`
                INSERT INTO tiles (server, map_id, x, y, file_path, hash, session_id, source)
                VALUES (?, ?, ?, ?, ?, ?, ?, 'collector')
                ON CONFLICT(server, map_id, x, y) DO UPDATE SET
                    file_path = excluded.file_path,
                    hash = excluded.hash,
                    collected_at = datetime('now'),
                    session_id = excluded.session_id,
                    source = 'collector'
            `, [server, mapId, x, y, destPath, hash, this.sessionId]);

            // Store version
            db.run(`
                INSERT INTO tile_versions (server, map_id, x, y, file_path, hash, session_id, source)
                VALUES (?, ?, ?, ?, ?, ?, ?, 'collector')
            `, [server, mapId, x, y, destPath, hash, this.sessionId]);

            this.tileCount++;
            this.pendingStitchCount++;

            // Broadcast
            const tile = { server, map_id: mapId, x, y, file_path: destPath };
            broadcastTileUpdate(tile);
            broadcastTileActivity({ server, map_id: mapId, action: 'collect', x, y });
            logActivity(server, mapId, 'collect', x, y, `Collected tile (session: ${this.sessionId})`);

            console.log(`[Collector] Tile (${x}, ${y}) — total: ${this.tileCount}`);

            // Auto-stitch check
            if (config.collector.autoStitch && this.pendingStitchCount >= config.collector.stitchThreshold) {
                this.triggerStitch(server);
            }
        } catch (err) {
            console.error(`[Collector] Error processing tile (${x}, ${y}):`, err.message);
        }
    }

    async triggerStitch(server) {
        this.pendingStitchCount = 0;
        try {
            const { stitchMap } = require('../stitcher/stitch');
            await stitchMap(server);
        } catch (err) {
            console.error('[Collector] Stitch error:', err.message);
        }
    }
}

module.exports = { TileCollector };
